name: emobs
main: com.ivanit.emobs.Emobs
version: 1.0
api-version: 1.15
commands:
   eMob:
      description: spawn an elemental mob
      usage: /<command> <mobName>
   eItem:
      description: spawn an elemental item
      usage: /<command> <itemName>